/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.43
 * Generated at: 2021-06-15 14:39:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.util.Date;
import java.text.SimpleDateFormat;

public final class adminsupplier_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("    <head>\n");
      out.write("            <meta charset=\"UTF-8\" content=\"width=device-width,initial-scale=1.0\">\n");
      out.write("             <title>Yashshree Egg Suppliers</title>\n");
      out.write("             <link href=\"https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\" rel=\"stylesheet\">\n");
      out.write("              <link href=\"border.css\" rel=\"stylesheet\">\n");
      out.write("              <link href=\"menu.css\" rel=\"stylesheet\">\n");
      out.write("       <style>\n");
      out.write("            td,th{\n");
      out.write("                padding: 10px;\n");
      out.write("                color: #eee6e2;\n");
      out.write("                font-family: arial;\n");
      out.write("                font-size: 16px;\n");
      out.write("                border-bottom: 2px solid #f6a00b;\n");
      out.write("           }\n");
      out.write("            \n");
      out.write("          caption{\n");
      out.write("                font-family: serif;\n");
      out.write("                color: #eee6e2;\n");
      out.write("                font-size: 20px;\n");
      out.write("            }\n");
      out.write("        </style>\n");
      out.write("    </head>\n");
      out.write("    <body bgcolor=\"#292929\">\n");
      out.write("      <div class=\"menu-bar\" >\n");
      out.write("        <ul>\n");
      out.write("       <img src=\"Images/icon11.png\" width=\"55\" height=\"55\"></img>\n");
      out.write("       <color>Yashshree Egg Suppliers</color> &nbsp; &nbsp; &nbsp;   \n");
      out.write("       <li class=\"active\"><a href=\"adminpage.jsp\">Home</a></li>\n");
      out.write("       <li align='right'><a href=\"#\">Suppliers</a></li>\n");
      out.write("        <li ><a href=\"customers.jsp\">Customer</a></li>\n");
      out.write("       <li><a href=\"adminegg.jsp\">Eggs</a></li>\n");
      out.write("        <li><a href=\"adminorder.jsp\">Orders</a></li>\n");
      out.write("       <li><a href=\"adminpayment.jsp\">Payment</a></li>\n");
      out.write("       <li><a href=\"adminlogin.jsp\">Log Out</a></li>\n");
      out.write("     </ul> \n");
      out.write("   </div>\n");
      out.write("       <div align='center' id=\"header\"> \n");
      out.write("        <br><br>\t\n");
      out.write("       <img   src=\"Images/hen8.jpg\" width=\"200\" height=\"200\" class=\"rcorner4\"></img>\n");
      out.write("       <img   src=\"Images/hen3.jpg\" width=\"200\" height=\"200\" class=\"rcorner4\"></img>\n");
      out.write("       <img   src=\"Images/egg1.jpg\" width=\"200\" height=\"200\" class=\"rcorner4\"></img>\n");
      out.write("       </div> \n");
      out.write("       <div align='center'>\n");
      out.write("      ");

      Class.forName("org.postgresql.Driver");
      Connection con=DriverManager.getConnection("jdbc:postgresql://localhost/ty","postgres","qwertyuiop");
      Statement st=con.createStatement();
      ResultSet rs=st.executeQuery("select * from supplier");
       out.print("<table cellspacing='0' width='800' >");
       out.print("<caption><b>Supplier Information</b></caption>");
       out.print("<tr bgcolor='#f6a00b' align='center'><th>Supplier ID</th><th>Name</th><th>Birthdate</th><th>Mobile</th><th>Address</th></tr>");
        while(rs.next())
          {
            out.print("<tr align='center'>");
            out.print("<td>"+rs.getInt(1));
            out.print("<td>"+rs.getString(2));

           SimpleDateFormat  sdf=new SimpleDateFormat("yyyy-mm-dd");
           Date d2=sdf.parse(rs.getString(3));
           sdf=new SimpleDateFormat("dd/mm/yyyy");
           out.print("<td class='border'>"+sdf.format(d2));
 
            out.print("<td>"+rs.getLong(4));
            out.print("<td>"+rs.getString(5));
             out.print("</tr>");
          }
             out.print("</table>");
        
      out.write("\n");
      out.write("  </div>\n");
      out.write("            <br>\n");
      out.write("             <br>            \n");
      out.write("           <table border=\"0\" width=\"100%\" height=\"250\" bgcolor=\"#292929\" id=\"contact\">\n");
      out.write("                 <tr align=\"right\"> \n");
      out.write("                  <td >\n");
      out.write("                 <a href=\"#header\"><font face=\"arial\" size=\"7\" color=\"#eee6e2\"><span class=\"fa fa-arrow-circle-up\" aria-hidden=\"true\"></span></font>\n");
      out.write("                  </a>\n");
      out.write("               </tr>\n");
      out.write("     </table>\n");
      out.write("       <br>\n");
      out.write("       <br>\n");
      out.write("   </body>\n");
      out.write("</html>\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
