/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.43
 * Generated at: 2021-06-15 08:19:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.util.Date;

public final class suppliereditac_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {


       HttpSession hs;
       String S;
       Connection con;
       Statement st;

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Date");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("    <head>\n");
      out.write("            <meta charset=\"UTF-8\" content=\"width=device-width,initial-scale=1.0\">\n");
      out.write("             <title>Yashshree Egg Suppliers</title>\n");
      out.write("             <link href=\"https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\" rel=\"stylesheet\">\n");
      out.write("              <link href=\"border.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("              <link href=\"menu.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("              <link href=\"help.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("    </head>\n");
      out.write("    <body bgcolor=\"#292929\">\n");
      out.write("      <div class=\"menu-bar\" id=\"header\">\n");
      out.write("        <ul>\n");
      out.write("       <img src=\"Images/icon11.png\" width=\"55\" height=\"55\"></img>\n");
      out.write("       <color>Yashshree Egg Suppliers</color>\n");
      out.write("       &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\n");
      out.write("         <li class=\"active\"><a href=\"supplierpage.jsp\">Home</a></li>\n");
      out.write("       <li><a href=\"supplieregg.jsp\">Eggs </a></li>\n");
      out.write("       <li><a href=\"supplierorder.jsp\">Orders</a>\n");
      out.write("        </li>\n");
      out.write("       <li><a href=\"supplierpayment.jsp\">Payment</a></li>\n");
      out.write("        <li><a href=\"about.html\">About</a></li>      \n");
      out.write("        <li><a href=\"#\">\n");
      out.write("       <span class=\"fa fa-user-circle\" aria-hidden=\"true\"></span>\n");
      out.write("       ");
          
           hs=request.getSession(true);  //In java default timeout for session is 30 minutes
           //This value is specified in web.xml. We can change timout value in web.xml
           S=(String)hs.getAttribute("supplier");
            if(S!=null)
            out.print(S); 
            else
            out.print("<script>alert('Your Session has been expired'); window.location.assign('supplierlogin.jsp');</script>");            
      
      out.write("\n");
      out.write("        </a>\n");
      out.write("           <div class=sub-menu-2>\n");
      out.write("              <ul>\n");
      out.write("                 <li><a href=\"supplieraccount.jsp\">Account</a></li>\n");
      out.write("                 <li><a href=\"supplierlogin.jsp\">Log Out</a></li>                    \n");
      out.write("               </ul>\n");
      out.write("           </div>\n");
      out.write("         </li>\n");
      out.write("       </ul> \n");
      out.write("   </div>\n");
      out.write("\n");
      out.write("      <div style=\"background-image: linear-gradient(rgba(0,0,0,0.8),rgba(0,0,0,0.7)),url(Images/egg3.jpg); background-position: center; background-size: cover; height: 150vh; \">\n");
      out.write("      <br><br><br><br>\n");
      out.write("      ");

       Class.forName("org.postgresql.Driver");
       Connection con=DriverManager.getConnection("jdbc:postgresql://localhost:5432/ty","postgres","qwertyuiop");
       Statement st=con.createStatement();
        ResultSet rs=st.executeQuery("select * from supplier where sid=(select sid from supplier_login where username='"+S+"')");
        ResultSet rs1=st.executeQuery("select password from supplier_login where username='"+S+"'");
        String pass=null;
        if(rs1.next()) 
        pass=rs1.getString(1);
       out.print("<table  border='2' style='border-radius: 7px; border-color: #f6a00b; margin: 0 auto;'  width='400' height='570' cellspacing='0' cellpadding='0' rules='none'>");
       out.print("<tr align='center'><td colspan='2'><font  class='form'  size='6'><b><span class='fa fa-user-circle' aria-hidden='true'></span></b></font>");
       out.print("<font class='form'  size='5'><b> Your Account Information</b></font><br><br></tr>");
       out.print("<form method='post' action='suppliereditac.jsp' id='edit'>");
        
        while(rs.next())
          {            
      // We can keep text field totally uninteractive using disabled keyword.
      out.print("<tr align='center'><td style='font-family: arial; color: #eee6e2; font-size:13pt;'>Username :<td><input type='text' name='t1' value='"+S+"' ></tr>");
      out.print("<tr align='center'><td  style='font-family: arial; color: #eee6e2; font-size:13pt;' width='30%'>Password :<td><input type='password' name='t2' value='"+pass+"' ></tr>");
      out.print("<tr align='center'><td  style='font-family: arial; color: #eee6e2; font-size:13pt;'>Name :<td><input type='text' name='t3' value='"+rs.getString(2)+"' ></tr>");
      out.print("<tr align='center'><td  style='font-family: arial; color: #eee6e2; font-size:13pt;'>Birthdate :<td><input type='date' name='t4' value='"+rs.getString(3)+"' ></tr>");
      out.print("<tr align='center'><td  style='font-family: arial; color: #eee6e2; font-size:13pt;'>Phone :<td><input type='text' name='t5' value='"+rs.getLong(4)+"' ></tr>");
      out.print("<tr align='center'><td  style='font-family: arial; color: #eee6e2; font-size:13pt;'>Address :<td><input type='text' name='t6' value='"+rs.getString(5)+"'></tr>");
      out.print("<tr><td colspan='2' height='70' align='center' valign='center'><input type='submit' value='Update Account'></tr>");                   
      out.print("</form>");           
      out.print("</table>");
         }    
      
      out.write("\n");
      out.write("    <font class=\"form\" size=\"4\"><center>\n");
      out.write("     ");

       Class.forName("org.postgresql.Driver");
       con=DriverManager.getConnection("jdbc:postgresql://localhost:5432/ty","postgres","qwertyuiop");
        if(S==null)
        out.print("<script>alert('Your Session has been expired'); window.location.assign('custlogin.jsp');</script>");            
        st=con.createStatement();     
        String a1=request.getParameter("t1");
        String a2=request.getParameter("t2");
        String a3=request.getParameter("t3");
        String a4=request.getParameter("t4");
        String a5=request.getParameter("t5");
        String a6=request.getParameter("t6");
         ResultSet r;
         if(a1!=null)
          {
             r=st.executeQuery("select sid from supplier_login where username='"+S+"'");  
             int sid=0;
             if(r.next())
             sid=r.getInt(1);
             try{
             st.executeUpdate("update supplier_login set username='"+a1+"' where username='"+S+"'");

              if(a2.length()<4) 
              out.print("<script> alert('Password must contain atleast 4 characters') </script>");                  
              else
              st.executeUpdate("update supplier_login set password=crypt('"+a2+"',gen_salt('bf')) where username='"+a1+"'");

              st.executeUpdate("update supplier set sname='"+a3+"' where sid="+sid);
              st.executeUpdate("update supplier set sbday='"+a4+"' where sid="+sid);
 
            try{
             st.executeUpdate("update supplier set sphone="+a5+" where sid="+sid);
             }
             catch(Exception e)
             {
               out.print("<script> alert('Mobile number already exist') </script>");
             }

              st.executeUpdate("update supplier set saddr='"+a6+"' where sid="+sid);

              out.print("<script>alert('Account Updated Successfully. Login with new details'); window.location.assign('supplierlogin.jsp'); </script>");    
           }
          catch(Exception e)
            {
                 out.print("<script> alert('Username already exist. Choose another name') </script>");
            }
       }               
  
      out.write("\n");
      out.write("        </center>\n");
      out.write("      </font>\n");
      out.write("    </div>\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
